export const me = new Map()
    .set('h1','Queval Moreno Loïc')
    .set('.intro','Connaissances en language informatique et en électronique')
    .set('#number','06 38 86 99 73')
    .set('#street','1 rue Pierre Dac 92110 Clichy')
    .set('#mail','queval.loic@gmail.com')
    .set('#birthday','11 juin 1997')
    .set('#gender','Homme')
    .set('#code1','Langages C')
    .set('#code2','PHP')
    .set('#code3','HTML 5')
    .set('#code4','CSS 3')
    .set('#code5','MSQL')
    .set('#code6','Javascript')
    .set('#code7','Jquery')

    .set('#langue-lu1','Anglais lu : Très bien ')
    .set('#langue-lu2','Espagnol lu : Bien ')
    .set('#langue-entendu1','Anglais entendu : bien')
    .set('#langue-entendu2','Espagnol entendu: Très bien ')
    .set('#langue-parlé1','Anglais parlé : Notions')
    .set('#langue-parlé2','Espagnol parlé : Notions')

    .set('#qualités','Organisé, Sérieux, Patient, Travail en équipe')
    .set('#activité','Centres d\'intérêt : Livres, Informatique, Jeux Vidéo, Echecs')
    .set('#sport','Sports : Judo (4 ans, Coupe Technique), Handball (3 ans, catégorie minimes, champion interdistrict), Badminton (2 ans, catégorie cadet)')
    .set('#lycée1','Lycée Louis Armand à Nogent-sur-Marne')
    .set('#matière1','Systèmes numériques - option électronique et communications')
    .set('#lycée2','Lycée Newton à Clichy-sur-Seine :')
    .set('#matière2','Sciences et technologies de l\'industrie et du développement durable - option Système d\'information numérique (mention assez bien)')
    .set('#entreprise1','Intérimaire chez Adecco')
    .set('#entreprise2','Leclerc à Gennevilliers :')
    .set('#poste','Responsable du rayon liquide')
    .set('#entreprise3','EANET à La Garenne Colombe :')
    .set('#stage','Stage de 6 semaines dans une entreprise de site internet personnalisé à la demande')
;