export const me = new Map()
    .set('#langue1-lu1',': Très bien')
    .set('#langue1-lu2','Anglais lu ')
    .set('#langue1-entendu1',': bien')
    .set('#langue1-entendu2','Anglais entendu ')
    .set('#langue1-parlé1',': notions')
    .set('#langue1-parlé2','Anglais parlé')
    .set('#langue1-entendu1',': bien')
    .set('#langue1-entendu2','Anglais entendu ')
    .set('#langue1-parlé1',': notions')
    .set('#qualités','Organisé, Sérieux, Patient, Travail en équipe')
    .set('#activité','Centres d\'intérêt : Livres, Informatique, Jeux Vidéo, Echecs')
    .set('#sport','Sports : Judo (4 ans, Coupe Technique), Handball (3 ans, catégorie minimes, champion interdistrict), Badminton (2 ans, catégorie cadet)')
    .set('#lycée1','Lycée Louis Armand à Nogent-sur-Marne')
    .set('#matière1','Systèmes numériques - option électronique et communications')
    .set('#lycée2','Lycée Newton à Clichy-sur-Seine :')
    .set('#matière2','Sciences et technologies de l\'industrie et du développement durable - option Système d\'information numérique (mention assez bien)')
    .set('#entreprise1','Intérimaire chez Adecco')
    .set('#entreprise2','Leclerc à Gennevilliers :')
    .set('#poste','Responsable du rayon liquide')
    .set('#entreprise3','EANET à La Garenne Colombe :')
    .set('#stage','Stage de 6 semaines dans une entreprise de site internet personnalisé à la demande')
;